name: Build and Deploy

on:
  push:
    branches:
      - reusable

jobs:
  build-and-deploy:
    uses: muskan04yadav/spring_shared_workflow/.github/workflows/resuable.yml@main
    with:
        image_name: muskan04yadav/spring-petclinic:latest
        container_name: spring-petclinic-container
        repository_name: spring-petclinic
        tag: latest
    secrets:
        docker_username: ${{ secrets.DOCKER_USERNAME}}
        docker_password: ${{ secrets.DOCKER_PASSWORD}}